### ISSUE TITLE
Allow multiple CurrentExecution to be managed by framework?

### ISSUE THREAD

**Issue by htwashere** [mrpaulandrew/procfwk#61]
Hi, currently the framework can only handle one collection of pipelines (procfwk.Pipelines) and one execution (CurrentExecution) to be managed at any single time. It would be ideal if a higher level grouping to be allowed so that, we can define multiple sets of pipelines and dependencies, and then we have a capability to submit them as separate jobs, and have the framework to manage multiple jobs to be tracked by procfwk.CurrentExecution? Thank you.

**Comment by NJLangley** [comment]
That would be super useful for my current client too

**Comment by mrpaulandrew** [comment]
Hey, thanks for your feedback.

@htwashere @NJLangley 

Could you please help be in exploring this idea further....

Let's say:

- A new execution is triggered. It starts processing and running worker pipelines A,B,C.
- Then a second new execution is triggered which is going to run concurrently.

How would the second execution know what worker it is responsible for?...

1. Using some custom logic in a precursor to enable/disable workers?
2. Have the second execution detect what the first execution is already running and ignore those workers?

**Or**, are we saying, we want the same workers to be called a second time (even if not complete as part of the first run) because we want to pass some different parameters to the pipelines?

I'd be really keen to collaborate on this design here and better understand the use cases?

Many thanks

**Comment by NJLangley** [comment]
Hi @mrpaulandrew 

In our situation we want to be able to run different executions, usually of separate, unrelated pipelines simultaneously. Some of the reasons for this approach are:

- Significant number of modules designed to run independently. We don't want a framework ADF and DB per module to avoid infrastructure sprawl.
- Lots of data sources with different delivery times/cadences. Some sources have tight timings to get loads done and we need things to run as soon as the data is available.
- Changing the metadata for the load process, even if done via an automated process before an execution, changes the ETL definition from what is in source control. Having multiple defined batches solves this issue.

I have just implemented this as a PoC with my current client and will get the code on my fork in the next few days.

The way we have implemented it is by adding a new concept of a batch, sitting over the top of the stages/pipelines. We have a new table that maps the stage and pipelines onto the batches to allow reuse of pipelines, eg for subtly different daily/weekly/monthly loads. This allows running two (or more) batches at the same time. We have added an extra check to ensure that a new batch cannot be started if it shares a common pipeline with an already executing batch.

**Comment by mrpaulandrew** [comment]
@htwashere @NJLangley 
Thanks for your comments.

It sounds like you've both addressed this in a similar way (Batch/Containers) as a level above stages. Very cool.

I guess in each case my final question would be... How does the parent pipeline know which Batch/Container it should start an execution run for?... Is this simply handled with a parameter passed and set on the parent pipeline trigger?

- Weekly trigger > Parent > Param = Weekly Batch
- Daily trigger > Parent > Param = Daily Batch

I'd certainly be interested in seeing both your code implementations if there is an easy way to share them.

Cheers
Paul

**Comment by NJLangley** [comment]
@mrpaulandrew I'll try and get our implementation on the fork tomorrow. 

Another situation this can be useful for is splitting processing of large files out from smaller ones when the processing window is limited. For example, if you have a bunch of dimensions and small fact tables, and one or two large fact tables that take 80% of the total time, you may want the larger ones in their own batch so that the transform, load and serve stages can continue for the smaller files while the extract for the larger files finishes. The later stages for the larger files can check the data they need for the transforms has loaded before continuing.

In terms of the parent knowing what to do, in our situation we have paramaterised the parent to take an identifier for the batch. This is actually a string unique across batches (eg a web address slug), and we pass that through to the child, infant and worker pipelines too. Passing it along is not strictly required, as it is not used, but passing the param allows us to see the batch id from the ADF monitoring GUI easily.

**Comment by mrpaulandrew** [comment]
@NJLangley sure, sounds good.

I'm also thinking that to accompany the batch ID, we should have the concept of worker pipeline parameter sets. This way worker pipelines can be reused for different batches, but have the batch ID link to a parameter set and in turn a set of pipeline parameters.

**Comment by htwashere** [comment]
Hi @mrpaulandrew : yes you're correct, we simply added a parameter called "ContainerName" to be passed at the beginning of 02-Parent. We also plan to pass an array of ContainerNames at 01-Grandparent if necessary in the future. Sounds like our approach is very similar to @NJLangley's implementation.

I am less familiar with github forking. I'll figure out eventually how to send you our implementation. Regards, H.

**Comment by mrpaulandrew** [comment]
@htwashere @NJLangley 

Thanks again for your feedback, I'm going to take this forward with:
https://github.com/mrpaulandrew/procfwk/issues/72

.... and extend the framework with the higher level concept suggested. I like the name Batch.

I'll start working on this maybe tonight.

Cheers

**Comment by Mallik-G** [comment]
Hi @mrpaulandrew,

I too had a similar requirement to support multiple parallel executions. I approached it similarly except that I called the higher-level concept as "Job".

A Job is comprised of one or more stages.
Multiple jobs can run concurrently.
JobId is passed a parameter from the Parent pipeline's trigger and is made available to all lower levels. 
A combination of pipelines linked to all stages in a job is inserted into LocalExecution. 
Once the job is successful, logs related to a job are moved to ExecutionLog

Metadatadb changes include 
    - changes to Stages table to support Job and Stage Linking.
    - added JobId as a parameter to stored procs where needed.
    - few properties like OverrideRestart, FailureHandling are more job-specific, so moved to a new object named JobProperties table. 
    - framework level properties that will be common across jobs are kept in Properties Table.
    - related procs and functions are also developed

Examples of Jobs:

- Daily Sales Ingestion Job (JobId 1)
    - Ingestion stage (StageId 1)
        - CopyToDataLake (Pipeline 1)
    - Transformation Stage (StageId 2)
        - LaunchDatabricksJob (Pipeline 2)
    - Load Stage (StageId 3)
        - CopyToDW (Pipeline 3)

- Daily Marketing Egression Job (JobId 2)
    - Prepare Stage (StageId 4)
        - LaunchDatabricksJob (Pipeline 4)
    - Extract Stage (StageId 5)
        - CopyToSFTP ((Pipeline 5)

- Weekly Campaign Ingestion Job (JobId 3)
    - Ingestion stage (StageId 6)
        - CopyToDataLake (Pipeline 6)
    - Transformation Stage (StageId 7)
        - LaunchDatabricksJob (Pipeline 7)
    - Load Stage (StageId 8)
        - CopyToDW (Pipeline 8)

I didn't have much use for Grand Parent at my work setup. So, my idea was to have the ParentPipeline to have different triggers (schedule or tumbling) and to pass the JobId as a parameter to the pipeline 

When a worker pipeline is reused in a stage within the same job or across jobs, for example, LaunchDatabricksJob is a pipeline that gets reused a lot at my work where I need to pass different invocation params, class name and jar name as well to submit different apps/jars on to Databricks cluster. 
To do that, I just add a new entry into Pipelines table mapping the Stage and Pipeline (like a new pipeline instance) and that causes a new PipelineId to be created making this particular pipeline instance unique. This PipelineId will be used in the Pipeline Parameters table to associate parameters needed for that particular pipeline id (or pipeline instance). 

Examples of Jobs:

DailyTrigger-SalesIngestion => Scheduled At 3 AM Daily in AUS Time Zone => Parameter: JobId = 1

DailyTrigger-MarketingEgression => TumblingWindow trigger Scheduled at 4 AM Daily UTC => Parameter: JobId = 2

WeeklyTrigger-CampaignIngestion => Scheduled At 3 AM On Mondays in AUS Time Zone => Parameter: JobId = 3


I had this as a work-in-progress project in my local for some time, but after looking at recent conversations around this issue, I have pulled recent changes from the master branch, applied my changes (only metadata database changes) and pushed them to my fork. Planning to work on ADF Pipeline changes tonight and give a test end to end

Please have a look at the changes and let me know if it helps - 
https://github.com/Mallik-G/ADF.procfwk/tree/feature/mallik

Thanks,
Mallik

**Comment by mrpaulandrew** [comment]
@htwashere @NJLangley just to follow up. The batch execution dev is done. I'm currently testing and will probably release it next week, once the github pages and documentation is up to date.
Cheers
